# Generated by Django 4.2.4 on 2023-08-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('data_inicio_relacionamento', models.DateField()),
                ('tipo_cliente', models.CharField(choices=[('potencial', 'Potencial'), ('atual', 'Atual'), ('antigo', 'Antigo')], max_length=20)),
                ('status_conta', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso')], max_length=20)),
                ('idade', models.PositiveIntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('historico_interacoes', models.TextField(blank=True, null=True)),
                ('historico_compras', models.TextField(blank=True, null=True)),
                ('fonte_aquisicao', models.CharField(blank=True, max_length=100, null=True)),
                ('campanhas_marketing', models.TextField(blank=True, null=True)),
                ('tarefas', models.TextField(blank=True, null=True)),
                ('interesses', models.TextField(blank=True, null=True)),
                ('historico_suporte', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('perfil_social', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
